name: travelapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_field: ^0.0.8
  image_input: ^0.0.2
  image_picker: ^1.0.5
  drop_down_list: ^0.0.6
  dropdown_search: ^5.0.6
  http: ^1.2.0
  logger: ^2.0.2+1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  fancy_button_flutter: ^1.0.3+1
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/google.png
    - img/apple_icon.png
    - img/df.png
    - img/profile_icon.png
    - img/mail.png
    - img/Temple.png
    - img/Aswan.png
    - img/abu_simbel.jpeg
    - img/detectionphoto.jpg
    - img/karnak.jpg
    - img/pyramids1.jpg
    - img/Musum.jpg
    - img/beaches.jpg
    - img/mountains.jpg
    - img/oasis.webp
    - img/diving.jpg
    - img/nile.jpg
    - img/sound-and-lights-hows.webp
    - img/ballon.jpg
    - img/c5.jpg
    - img/sphinx.webp
    - img/Step Pyramid of Saqqara & Saqqara Necropolis.webp
    - img/Valley-Of-The-Kings.jpg
    - img/Valley-of-the-queens.jpg
    - img/denderaext.jpg
    - img/Luxor_Temple.jpg
    - img/philae.webp
    - img/Kom-Ombo.png
    - img/Colossi-of-Memnon.jpg
    - img/Medinet Habu.jpg
    - img/Ramesseum.jpg
    - img/Tombs of Sennoferjpg.jpg
    - img/Tomb-of-Ramses-VI.jpg
    - img/tombs-of-the-nobels.jpg
    - img/temple-of-seti.jpg
    - img/tut.jpg
    - img/Tomb of Ramses III.jpg
    - img/Qubbet-El-Hawa.jpg
    - img/Temple-of-edfu.jpg
    - img/Temple of Hatshepsut.jpg
    - img/Oases/Bahariya_oasia.jpg
    - img/Oases/Dakhla_Osasis.jpg
    - img/Oases/Farafra-Oasis.jpg
    - img/Oases/Kharga_Oasis.jpg
    - img/Oases/Siwa-Oasis.png
    - img/Oases/Wadi El-Rayan.jpg
    - img/Beaches/agiba_beach.jpg
    - img/Beaches/el_gouna.jpg
    - img/Beaches/fjord_bay_taba.jpg
    - img/Beaches/mahmya_island.jpg
    - img/Beaches/nuweiba.jpg
    - img/Beaches/ras_abu_galoum.jpg
    - img/Beaches/ras_um_sid.jpg
    - img/Beaches/sahl_hasheesh_beach.jpg
    - img/Beaches/sharm_el_luli.jpg
    - img/Museums/IslamicArt.png
    - img/Museums/Luxor.jpg
    - img/Museums/Manial Palace Museum.png
    - img/Museums/nubian.jpg
    - img/Museums/The copic.png
    - img/Museums/The-Egyptiam-Museum-Egypt.jpg
    - img/Museums/The-Grand-Egyptian-Museum.jpg
    - img/Museums/The-National-Museum-of-Egyptian-Civilization.jpg
    - img/Museums/PortSaid.jpg
    - img/Mountains/63_full.jpg
    - img/Mountains/142287-شايب-البنات.jpg
    - img/Mountains/Marsa_Alam_-_Red_Sea.jpg
    - img/Mountains/Mount_Moses.jpg
    - img/Mountains/SiwaMautaWestSide.jpg
    - img/Mountains/The_perspective_of_the_galala_Plateau_Road_in_egypt.jpg
    - img/Mountains/جبل-الحلال-في-مصر.jpg
    - img/Statues/Khafre.webp
    - img/Statues/ramsis.jpg
    - img/Statues/tut.jpg
    - img/abuelhul.jpg
  


    
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
